@startuml
title PlantUML Studio Base ####
actor User
participant "Web editor" as Editor
participant plantUML
database LocalStorage

User -> Editor ++: Write a diagram
Editor -> LocalStorage++ : Save source
return : listSchema
Editor -> plantUML++ : reder diagram
return : Rendered diagram
return : affiche schéma

@enduml
